spring.datasource.url=jdbc:mysql://localhost/souzafood?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=souza
spring.datasource.password=123456

spring.flyway.locations=classpath:db/migration,classpath:db/testdata

spring.jpa.show-sql=true 
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect


spring.jackson.deserialization.fail-on-unknown-properties=true
spring.jackson.deserialization.fail-on-ignored-properties=true

#Explicação para as anotações abaixo: spring.mvc.throw-exception-if-no-handler-found=true e 
#spring.resources.add-mappings=false estão na aula: https://www.algaworks.com/aulas/1945/desafio-tratando-a-excecao-nohandlerfoundexception/
spring.mvc.throw-exception-if-no-handler-found=true 
spring.resources.add-mappings=false

server.compression.enabled=true

#https://app.algaworks.com/aulas/2266/configurando-a-validacao-de-jwt-no-resource-server-com-a-chave-publica
spring.security.oauth2.resourceserver.jwt.public-key-location=classpath:keys/souzafood-pkey.pem

#https://app.algaworks.com/aulas/2226/configurando-o-appender-do-loggly-no-logback
#logging.loggly.token=seu_customer_token_aqui

#Explicação para as anotações abaixo. Aula: https://app.algaworks.com/aulas/2238/configurando-o-resource-server-com-a-nova-stack-do-spring-security
#spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=http://auth.souzafood.local:8081/oauth/check_token
#spring.security.oauth2.resourceserver.opaquetoken.client-id=checktoken
#spring.security.oauth2.resourceserver.opaquetoken.client-secret=check123

# O thiago usa essa propiedade abaixo para debugar a aplicação na aula: https://app.algaworks.com/aulas/2260/configurando-o-resource-server-para-jwt-assinado-com-chave-simetrica 
#logging.level.org.springframework=DEBUG

# Storage
souzafood.storage.tipo=local
souzafood.storage.local.diretorio-fotos=/home/rodrigo/Documents/catalago
#souzafood.storage.s3.id-chave-acesso=
#souzafood.storage.s3.chave-acesso-secreta=
souzafood.storage.s3.bucket=souzafood-test
souzafood.storage.s3.regiao=us-east-1
souzafood.storage.s3.diretorio-fotos=catalago
souzafood.storage.s3.url-buket=https://souzafood-test.s3.amazonaws.com

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
#spring.mail.password=

#Caso precise que a propiedade souzafood.email.remetente= do application.properties fique dinamica
#Implementação feita no forum e suporte https://www.algaworks.com/forum/topicos/84402/duvida-na-propiedade-remetente#90859
souzafood.email.remetente=SouzaFood <souzaafood@gmail.com>

#https://www.algaworks.com/aulas/2086/formatando-valores-monetarios-com-ftl
spring.freemarker.settings.locale=pt_BR
souzafood.email.impl=fake
souzafood.email.sandbox.destinatario=rdsouza.c@gmail.com

 
#Propiedade para escolher o tipo de armazenamento se informado s3 o armazenado sera feito no s3 se informa local sera armazenado local

#Caso você queria fazer upload de arquivos maiores configure as propiedades do spring com valores maiores. 
#Aula https://www.algaworks.com/aulas/2055/validando-o-tamanho-maximo-do-arquivo
#spring.servlet.multipart.max-file-size=20MB
#spring.servlet.multipart.max-request-size=20MB

#spring.jackson.property-naming-strategy=SNAKE_CASE

#spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=create

#spring.jpa.properties.javax.persistence.schema-generation.scripts.action=create
#spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target=src/main/resources/ddl.sql

#spring.datasource.hikari.maximum-pool-size=5
#spring.datasource.hikari.minimum-idle=3
#spring.datasource.hikari.idle-timeout=10000
